export const ActionTypes = {
  SET_BUGS: "SET_BUGS",
  SELECTED_BUG: "SELECTED_BUG",
  REMOVE_SELECTED_BUG: "REMOVE_SELECTED_BUG",
  DELETE_BUG: "DELETE_BUG",
  CREATE_BUG: "CREATE_BUG",
  UPDATE_BUG: "UPDATE_BUG",
};
