export const ActionTypes = {
    SET_PROJECTS : 'SET_PROJECTS',
    SELECTED_PROJECT: 'SELECTED_PROJECT',
    REMOVE_SELECTED_PROJECT:'REMOVE_SELECTED_PROJECT',
    DELETE_PROJECT:'DELETE_PROJECT',
    CREATE_PROJECT:'CREATE_PROJECT',
    UPDATE_PROJECTS:'UPDATE_PROJECTS',
    UPDATE_PROJECT:'UPDATE_PROJECT',
}