const mongoose = require("mongoose");
const User = require("../models/user");

const seedUsers = [
  new User({
    _id: mongoose.Types.ObjectId("000000000000000000000000"),
    email: "deletedUser@live.com",
    assignedBugs: [],
    comments: [],
    role: "Deleted",
    uid: "4iZTTHtRTpVgBbKJmERBlB2BpIF2",
    name: "Deleted User",
    assignable: false,
    deleted: true,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07c"),
    email: "hllam@live.com",
    project: "63ab7ace4e39c16c9b79e3ac",
    assignedBugs: ["63ab78cc81174e7f3a98fd0e"],
    comments: [],
    uid: "ADhHPJnIh5gaE0yrWcCID8KhEQn1",
    role: "Developer",
    name: "Hillard Amerigo",
    assignable: false,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07d"),
    email: "jadavis@verizon.net",
    project: "63ab7ace4e39c16c9b79e3ac",
    comments: [],
    assignedBugs: [],
    uid: "bjyglte3H1Y0eghVkQyia4s652X2",
    role: "Developer",
    name: "James Davis",
    assignable: false,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07e"),
    email: "flaviog@msn.com",
    project: "63ab7ace4e39c16c9b79e3ac",
    comments: [],
    assignedBugs: [],
    uid: "7LzLmAWeTnSGyBUcNIezArzEZee2",
    role: "Developer",
    name: "Filip Mendez",
    assignable: false,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07f"),
    email: "lenz@sbcglobal.net",
    uid: "7i3EJNn8UQUjOf1F6TNUJrUWByu2",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Lennie Zapper",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf080"),
    email: "glenz@sbcglobal.net",
    uid: "Tkviefr3G7WxKR3RhbwyFtT3BlE3",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Gill Lenz",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf081"),
    email: "durist@comcast.net",
    uid: "2MqkVzdIc4SxkaUwhluUkyuiWp42",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Durant Williams",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf082"),
    email: "stomv@hotmail.com",
    uid: "LGGTxeIQcaWCV9KyOuIoO4QxSp93",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Storm Victor",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf083"),
    email: "mschwartz@sbcglobal.net",
    uid: "EyQWiqdFHbNfWrzC5lo51dcpHFX2",
    comments: [],
    assignedBugs: [],
    name: "Emily Schwartz",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf084"),
    email: "bryanw@hotmail.com",
    uid: "ciEapaHyEtNlETxmm7Ju7F8KyUW2",
    comments: [],
    assignedBugs: [],
    name: "Bryan Woodard",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf085"),
    email: "chaikin@aol.com",
    uid: "RoDsXf0Mc7gPsYf3tzzbiJTGU7h1",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Chai Kinsworth",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf086"),
    email: "phish@verizon.net",
    uid: "CKMZfqzakpa5eQtUxbZgdn0P7Ih1",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Phoebe Phish",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf087"),
    email: "jramio@msn.com",
    uid: "Y0HYlLEzWLd2Ex8eYDK6VFnUohJ2",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Jerome Ramio",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf088"),
    email: "pakaste@yahoo.ca",
    uid: "ijDn7f3cKzTj8y4xiWDXGUq17hB2",
    assignedBugs: [],
    comments: [],
    role: "Developer",
    name: "Nene Nene",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf089"),
    email: "am@live.com",
    uid: "uJMbVJPyaGcr0OP3nqfmgujBUeg2",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Amber Michelle",
  }),
  new User({
    _id: new mongoose.Types.ObjectId(),
    email: "demodeveloper@gmail.com",
    uid: "qlrmJPCKxETb37OKOx8KVWWXetc2",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Demo Developer",
  }),
  new User({
    _id: new mongoose.Types.ObjectId(),
    email: "demoadmin@gmail.com",
    uid: "cASZy98Ay3P4r69AMQaojvRSw1m1",
    comments: [],
    assignedBugs: [],
    role: "Admin",
    name: "Demo Admin",
    assignable: false,
  }),
];

module.exports = seedUsers;
