const mongoose = require("mongoose");
const User = require("../models/user");

const seedUsers = [
  new User({
    _id: mongoose.Types.ObjectId("000000000000000000000000"),
    email: "deletedUser@live.com",
    assignedBugs: [],
    comments: [],
    role: "Deleted",
    name: "Deleted User",
    assignable: false,
    deleted: true,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07c"),
    email: "hllam@live.com",
    project: "63ab7ace4e39c16c9b79e3ac",
    assignedBugs: ["63ab78cc81174e7f3a98fd0e"],
    comments: [],
    role: "Developer",
    name: "Hillard Amerigo",
    assignable: false,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07d"),
    email: "jadavis@verizon.net",
    project: "63ab7ace4e39c16c9b79e3ac",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "James Davis",
    assignable: false,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07e"),
    email: "flaviog@msn.com",
    project: "63ab7ace4e39c16c9b79e3ac",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Filip Mendez",
    assignable: false,
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf07f"),
    email: "lenz@sbcglobal.net",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Lennie Zapper",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf080"),
    email: "glenz@sbcglobal.net",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Gill Lenz",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf081"),
    email: "durist@comcast.net",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Durant Williams",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf082"),
    email: "stomv@hotmail.com",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Storm Victor",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf083"),
    email: "mschwartz@sbcglobal.net",
    comments: [],
    assignedBugs: [],
    name: "Emily Schwartz",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf084"),
    email: "bryanw@hotmail.com",
    comments: [],
    assignedBugs: [],
    name: "Bryan Woodard",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf085"),
    email: "chaikin@aol.com",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Chai Kinsworth",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf086"),
    email: "phish@verizon.net",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Phoebe Phish",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf087"),
    email: "jramio@msn.com",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Jerome Ramio",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf088"),
    email: "pakaste@yahoo.ca",
    assignedBugs: [],
    comments: [],
    role: "Developer",
    name: "Nene Nene",
  }),
  new User({
    _id: mongoose.Types.ObjectId("63a36a4d3f0f5cf676acf089"),
    email: "am@live.com",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Amber Michelle",
  }),
  new User({
    _id: new mongoose.Types.ObjectId(),
    email: "DemoDeveloper@gmail.com",
    comments: [],
    assignedBugs: [],
    role: "Developer",
    name: "Demo Developer",
  }),
  new User({
    _id: new mongoose.Types.ObjectId(),
    email: "DemoAdmin@gmail.com",
    comments: [],
    assignedBugs: [],
    role: "Admin",
    name: "Demo Admin",
    assignable: false,
  }),
];

module.exports = seedUsers;
