export const ActionTypes = {
    SET_USERS : 'SET_USERS',
    SELECTED_USER: 'SELECTED_USER',
    LOGOUT:'LOGOUT',
    DELETE_USER:'DELETE_USER',
    CREATE_USER:'CREATE_USER',
    UPDATE_USERS:'UPDATE_USERS',
    UPDATE_USER:'UPDATE_USER',
    SET_LOGIN_METHODS:'SET_LOGIN_METHODS',
    REMOVE_LOGIN_METHODS:'REMOVE_LOGIN_METHODS',
}